name: Create Daily Logs

on:
    schedule:
        # Runs at UTC midnight and 8 AM IST (2:30 UTC)
        - cron: "0 0 * * *"
        - cron: "30 2 * * *"
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
    run-cron:
        runs-on: ubuntu-latest
        steps:
            - name: Call Create Daily Logs API
              run: |
                  curl --request POST \
                  --url '${{ secrets.APP_URL }}/api/v1/cron/create-daily-logs' \
                  --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'