name: Process Account Deletions

on:
    schedule:
        # Runs at UTC midnight and 8 AM IST (2:30 UTC)
        - cron: "10 0 * * *" # Offset by 10 mins
        - cron: "40 2 * * *"
    workflow_dispatch:

jobs:
    run-cron:
        runs-on: ubuntu-latest
        steps:
            - name: Call Account Deletions API
              run: |
                  curl --request POST \
                  --url '${{ secrets.APP_URL }}/api/v1/cron/process-account-deletions' \
                  --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'