name: Send Weekly Summaries

on:
    schedule:
        # Runs on Sunday at 7 PM IST (13:30 UTC) and 10 PM IST (16:30 UTC)
        - cron: "30 13 * * 0"
        - cron: "30 16 * * 0"
    workflow_dispatch:

jobs:
    run-cron:
        runs-on: ubuntu-latest
        steps:
            - name: Call Weekly Summary API
              run: |
                  curl --request POST \
                  --url '${{ secrets.APP_URL }}/api/v1/cron/weekly-progress/report' \
                  --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
